# Generated by Django 3.1 on 2020-09-01 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweetpy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-id']},
        ),
    ]
